[build]
builder = "nixpacks"
buildCommand = "npm install && cp prisma/schema.production.prisma prisma/schema.prisma && npx prisma generate && npx prisma migrate deploy"

[deploy]
startCommand = "node src/index.js"
restartPolicyType = "on_failure"
